package com.educalab.filosofar.ui.navigation

object Routes {
    const val ONBOARDING = "onboarding"
    const val PROFILE_SETUP = "profile_setup"
    const val MAP = "map"
    const val ISLAND_DETAIL = "island/{islandId}"
    const val DAILY_QUESTION = "daily_question/{islandId}"
    const val DILEMMA_LIST = "dilemmas/{islandId}"
    const val DILEMMA_DETAIL = "dilemma/{dilemmaId}"
    const val REASON_CARDS = "reason_cards/{dilemmaId}"
    const val PERSPECTIVE_LIST = "perspectives/{islandId}"
    const val PERSPECTIVE_DETAIL = "perspective/{exerciseId}"
    const val LOGIC_LAB = "logic_lab/{islandId}"
    const val LOGIC_CHALLENGE = "logic_challenge/{challengeId}"
    const val SELF_DEBATE_LIST = "debates/{islandId}"
    const val SELF_DEBATE_DETAIL = "debate/{debateId}"
    const val OPINION_REVISION = "opinion_revision"
    const val JOURNAL = "journal"
    const val PROGRESS_COLLECTION = "progress"
    const val SETTINGS = "settings"

    fun islandDetail(islandId: String) = "island/$islandId"
    fun dailyQuestion(islandId: String) = "daily_question/$islandId"
    fun dilemmaList(islandId: String) = "dilemmas/$islandId"
    fun dilemmaDetail(dilemmaId: String) = "dilemma/$dilemmaId"
    fun reasonCards(dilemmaId: String) = "reason_cards/$dilemmaId"
    fun perspectiveList(islandId: String) = "perspectives/$islandId"
    fun perspectiveDetail(exerciseId: String) = "perspective/$exerciseId"
    fun logicLab(islandId: String) = "logic_lab/$islandId"
    fun logicChallenge(challengeId: String) = "logic_challenge/$challengeId"
    fun selfDebateList(islandId: String) = "debates/$islandId"
    fun selfDebateDetail(debateId: String) = "debate/$debateId"
}
